name: ota_update_fork
description: A Flutter plugin providing ota updates for Android and iOS, with download progress (Android only)
version: 6.0.0
homepage: https://github.com/shareven/ota_update_fork

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.12.13+hotfix.6"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: sk.fourq.otaupdate
        pluginClass: OtaUpdatePlugin
